# .cnb.yml
$:
  push:
    - name: docker-build-push
      services:
        - docker
      stages:
        - name: docker login
          script: docker login -u ${CNB_TOKEN_USER_NAME} -p "${CNB_TOKEN}" docker.cnb.cool
          
        - name: docker build
          script: docker build -f Dockerfile -t docker.cnb.cool/szsk968/webp_server_go .
          
        - name: docker push
          script: docker push docker.cnb.cool/szsk968/webp_server_go