FROM golang:1.25-trixie AS builder

ARG IMG_PATH=/opt/pics
ARG EXHAUST_PATH=/opt/exhaust
RUN apt update && apt install --no-install-recommends libvips-dev -y && mkdir /build
COPY go.mod /build
RUN cd /build && go mod download

COPY ./assets /build/assets
# Install libam with correct arch
RUN dpkg -i /build/assets/libaom3_3.11.0-1_$(dpkg --print-architecture).deb && \
    rm /build/assets/libaom3_3.11.0-1_$(dpkg --print-architecture).deb

COPY . /build

RUN cd /build && make && make test